Auth token working, dynamic scroll incomplete
karankarpe92/prediction-app pull request #9
Opened 2021-01-23 17:26 UTC by harshLFC

2021-01-23 18:20 UTC, sanketdayama commented on lib/services/auth.dart
> +
The or unusable code and print statements can be removed

2021-01-23 18:22 UTC, sanketdayama commented on lib/screens/prediction.dart
> +//       'chelsea',
These comments too can be removed

2021-01-23 18:24 UTC, sanketdayama requested changes
Hi Harsh, I have written some comments for Auth, for logic I just went through once maybe once I do the forgot password I'll get a better sense of it

2021-01-23 20:18 UTC, harshLFC commented
Sure

Regards
Harsh Phoujdar

On 23-Jan-2021, at 6:25 PM, sanketdayama <notifications@github.com> wrote:

﻿

@sanketdayama requested changes on this pull request.

Hi Harsh, I have written some comments for Auth, for logic I just went through once maybe once I do the forgot password I'll get a better sense of it

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/karankarpe92/prediction-app/pull/9#pullrequestreview-574866392>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AGEFKVDI6PPZTOOZKUZEQA3S3MIAJANCNFSM4WP2YQ5Q>.

2021-01-27 21:28 UTC, harshLFC commented on lib/services/auth.dart
> +
Thanks, will do

2021-01-27 21:28 UTC, harshLFC commented on lib/screens/prediction.dart
> +//       'chelsea',
Ok

2021-03-17 21:24 UTC, closed without merging